"""durable artifact enrichment

Revision ID: 6af74a0d6909
Revises: 0118bda3e719
Create Date: 2026-09-20 17:32:27.516776

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6af74a0d6909'
down_revision: Union[str, Sequence[str], None] = '0118bda3e719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_analysis_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('recipe', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('preserve_metadata', sa.Boolean(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_artifact_analysis_generations_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_artifact_analysis_generations_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_analysis_generations')),
    sa.UniqueConstraint('file_id', 'source_sha256', 'recipe', name='uq_artifact_analysis_recipe')
    )
    with op.batch_alter_table('artifact_analysis_generations', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_analysis_due', ['state', 'next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_analysis_generations_file_id'), ['file_id'], unique=False)

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_selection_version', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('thumbnail_generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_policy', sa.String(length=16), server_default='on_demand', nullable=False))
        batch_op.add_column(sa.Column('selection_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thumbnail_generations', schema=None) as batch_op:
        batch_op.drop_column('selection_version')
        batch_op.drop_column('processing_policy')

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_selection_version')

    with op.batch_alter_table('artifact_analysis_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_analysis_generations_file_id'))
        batch_op.drop_index('ix_artifact_analysis_due')

    op.drop_table('artifact_analysis_generations')
    # ### end Alembic commands ###
